variables:
  # 版本号，默认取流水线ID
  VERSION_NUMBER: "0.1.$CI_PIPELINE_ID"
  # 镜像tag: staging-0.0.x
  IMAGE_TAG: "staging-$VERSION_NUMBER"

deploy-staging:
  stage: deploy
  tags:
    - build-in-docker
  image: registry.devops.rivtower.com/library/helmfile/helmfile:v0.169.1
  needs:
    - send-helm
  variables:
    KUBECONFIG: $KUBERNETES_RIVTOWER_STAGING_248_CCSE
  script:
    - helmfile -e staging apply -f ci/helm/helmfile.yaml

include:
  - local: 'ci/pipelines/common.yml'
