image: node:22-alpine

workflow:
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /skip-ci/
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - when: always

variables:
  # 如: rivtrust/rivdap/nft-frontend
  IMAGE_NAME: "$RIVTOWER_REGISTRY_ADDRESS/web5/bbs-fe"
  # chart仓库地址
  CHART_REPO: "https://$RIVTOWER_REGISTRY_ADDRESS/chartrepo/web5"
  # 仓库名
  CHART_REPO_NAME: "web5"
  # chart name
  CHART_NAME: "bbs-fe"

stages:
  - build
  - send-helm
  - deploy

null-job:
  stage: build
  script: "exit 0"
  only:
    - __not_exist__

include:
  - local: 'ci/pipelines/development.yml'
    rules:
      - if: $CI_COMMIT_BRANCH == "develop"

  - local: 'ci/pipelines/staging.yml'
    rules:
      - if: $CI_COMMIT_BRANCH == "test"
      - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "test"

  - local: 'ci/pipelines/release.yml'
    rules:
      - if: $CI_COMMIT_TAG =~ /^release-/
