environments:
  development:
  staging:

---

repositories:
  - name: web5
    url: https://registry.devops.rivtower.com/chartrepo/web5
    username: {{ requiredEnv "RIVTOWER_REGISTRY_USERNAME" }}
    password: {{ requiredEnv "RIVTOWER_REGISTRY_PASSWORD" }}

helmDefaults:
  wait: true
  timeout: 600

releases:
  - name: bbs-fe
    namespace: web5
    chart: web5/bbs-fe
    version: {{ requiredEnv "VERSION_NUMBER" }}
    values:
      - ./values/{{ .Environment.Name }}.yaml