apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mintpad-fe.fullname" . }}
  labels:
    {{- include "mintpad-fe.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mintpad-fe.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mintpad-fe.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          {{- if .Values.env.enable }}
          volumeMounts:
            - name: env-config
              mountPath: /app/.env
              subPath: .env
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- if .Values.env.enable }}
      volumes:
        - name: env-config
          configMap:
            name: {{ include "mintpad-fe.fullname" . }}-env
      {{- end }}
